<?php
/**
 * @var $block \Idlbridge\Storelist\Block\Website\Block
 */
?>
<div class="switcher store switcher-store" id="switcher-store">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Store')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($block->getWebsiteCollection() as $_group) : ?>
            <?php if ($_group->getId() == $block->getCurrentGroupId()) : ?>
                <div class="action toggle switcher-trigger"
                     role="button"
                     tabindex="0"
                     data-mage-init='{"dropdown":{}}'
                     data-toggle="dropdown"
                     data-trigger-keypress-button="true"
                     id="switcher-store-trigger">
                    <strong>
                        <span><?= $block->escapeHtml($_group->getName()) ?></span>
                    </strong>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($block->getWebsiteCollection() as $_group) : ?>
                <?php if (!($_group->getId() == $block->getCurrentGroupId())) : ?>
                    <li class="switcher-option">
                        <a href="<?php echo  $_group->getDefaultStore()->getCurrentUrl() ?>">
                            <?= $block->escapeHtml($_group->getName()) ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
